<?php
// Generated by AI
// Configuration de la connexion PostgreSQL
// Ajuste ces valeurs selon ton installation locale.
return [
    'host' => 'localhost',
    'port' => 5432,
    'dbname' => 'testdb',
    'user' => 'postgres',
    'password' => 'postgres',
];

// Generated by AI END