<?php

$redis = new Redis();
$redis->connect('127.0.0.1', 6379);

// Generated by AI
function sqlToSnakeCase($query) {
    // Remove extra spaces and line breaks
    $query = preg_replace('/\s+/', ' ', trim($query));
    // Find all words (table/column names) in the query
    return strtolower(preg_replace('/([a-z])([A-Z])/', '$1_$2', $query));
}
// Generated by AI END